import base64
import edge_tts

VOICE_MAP = {
    'hi': 'hi-IN-SwaraNeural',
    'gu': 'gu-IN-DhwaniNeural',
    'es': 'es-ES-ElviraNeural',
    'fr': 'fr-FR-DeniseNeural',
    'en': 'en-US-AriaNeural'
}

async def generate_audio_stream(text: str, lang_code: str) -> str:
    try:
        voice = VOICE_MAP.get(lang_code, 'en-US-AriaNeural')
        communicate = edge_tts.Communicate(text, voice)
        
        audio_data = b""
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_data += chunk["data"]
                
        if not audio_data:
            raise ValueError("No audio data generated by Edge TTS")
            
        return base64.b64encode(audio_data).decode('utf-8')
    except Exception as e:
        print(f"Neural TTS generation error, falling back to silence: {e}")
        return generate_silent_fallback()

def generate_silent_fallback() -> str:
    import struct
    num_samples = 8000  # 1 second at 8000Hz
    data = b'\x80' * num_samples  # 128 (0x80) is silence for 8-bit PCM
    
    header = struct.pack('<4sI4s4sIHHIIHH4sI',
        b'RIFF',
        36 + num_samples,
        b'WAVE',
        b'fmt ',
        16,      # Subchunk1Size
        1,       # AudioFormat (PCM)
        1,       # NumChannels (Mono)
        8000,    # SampleRate
        8000,    # ByteRate
        1,       # BlockAlign
        8,       # BitsPerSample
        b'data',
        num_samples
    )
    
    wav_bytes = header + data
    return base64.b64encode(wav_bytes).decode('utf-8')
