import base64
import edge_tts
from typing import Optional

VOICE_MAP = {
    'hi': 'hi-IN-SwaraNeural',
    'gu': 'gu-IN-DhwaniNeural',
    'es': 'es-ES-ElviraNeural',
    'fr': 'fr-FR-DeniseNeural',
    'en': 'en-US-AriaNeural'
}

async def generate_audio_stream(text: str, lang_code: str) -> Optional[str]:
    """Return natural neural speech, or None so clients can use a real fallback."""
    try:
        voice = VOICE_MAP.get(lang_code, 'en-US-AriaNeural')
        communicate = edge_tts.Communicate(text, voice, rate='+4%')
        
        audio_data = b""
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_data += chunk["data"]
                
        if not audio_data:
            raise ValueError("No audio data generated by Edge TTS")
            
        return base64.b64encode(audio_data).decode('utf-8')
    except Exception as e:
        print(f"Neural TTS generation error: {e}")
        return None
